version: '3'

services:
  postgres:
    image: postgres:13.5-alpine
    restart: always
    environment:
      POSTGRES_DB: thisdb
      POSTGRES_USER: myself
      POSTGRES_PASSWORD: mypassword
      TZ: UTC
    ports:
      - "5432:5432"
  zookeeper:
    image: docker.target.com/streaming/zookeeper-test:3.7.0.404
    hostname: zookeeper
    ports:
      - '2181:2181'
      - '2182:2182'
    environment:
      METRICS__ENABLED: false
  kafka:
    image: docker.target.com/streaming/kafka-test:2.8.1.140
    hostname: kafka
    ports:
      - '9091:9091'
      - '9092:9092'
      - '9093:9093'
    environment:
      METRICS__ENABLED: false
    depends_on:
      - zookeeper
